name: custom_pointed_popup
description: Popup that can be shown on any targeted widget with customized pointed design.
version: 0.0.4
author: Dipak Shrestha <dipak.shrestha@eemc.edu.np>
homepage: https://github.com/DipakShrestha-ADS/custom_pointed_popup

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
